# Generated by Django 5.1.15 on 2026-05-31 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_backfill_search_vector"),
        ("organizations", "0002_add_deleted_at_index"),
        ("workflows", "0001_create_workflow_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="workflowexecution",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True),
                    ("status__in", ["pending", "in_progress"]),
                ),
                fields=("document",),
                name="uq_wf_exec_one_active_per_document",
            ),
        ),
    ]
