# Generated by Django 5.1.15 on 2026-06-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_backfill_search_vector"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="ocr_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
