# Generated by Django 5.1.15 on 2026-07-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_add_document_ocr_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="thumbnail_key",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="document",
            name="thumbnail_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
